#!/usr/bin/env bash 

yabai -m config layout bsp
yabai -m config window_gap 06
yabai -m config mouse_modifier fn
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
yabai -m config mouse_drop_action swap
